# Generated by Django 5.2.7 on 2025-10-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0003_remove_ingredientes_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('es_parada_no_planificada', models.BooleanField(default=True, help_text='Si está marcado, se considera un incidente (parada no planificada). Si no, es una parada planificada.', verbose_name='¿Es parada no planificada?')),
                ('origen', models.CharField(choices=[('produccion', 'Producción'), ('mantenimiento', 'Mantenimiento'), ('general', 'General/No asociado')], max_length=20, verbose_name='Contexto de origen')),
                ('descripcion', models.TextField(verbose_name='Descripción del incidente')),
                ('requiere_acciones_correctivas', models.BooleanField(default=False, verbose_name='¿Requiere acciones correctivas?')),
                ('acciones_correctivas', models.TextField(blank=True, help_text='Descripción de las acciones correctivas aplicadas', verbose_name='Acciones correctivas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.maquina', verbose_name='Máquina asociada')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
