# Generated by Django 5.2.7 on 2025-10-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_observacion', models.DateField(db_index=True)),
                ('hora_registro', models.TimeField(default='09:00', verbose_name='Hora de Registro')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField()),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación General',
                'verbose_name_plural': 'Observaciones Generales',
                'ordering': ['-fecha_observacion', '-hora_registro'],
                'indexes': [models.Index(fields=['-fecha_observacion', 'hora_registro'], name='eventos_obs_fecha_o_e69eed_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidente', models.DateField(db_index=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField()),
                ('acciones_correctivas', models.BooleanField(default=False)),
                ('detalle_acciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('contexto_origen', models.CharField(choices=[('PRODUCCION', 'Producción'), ('MANTENIMIENTO', 'Mantenimiento'), ('GENERAL', 'General')], max_length=20)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_incidentes', to='catalogos.maquina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_incidentes', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_incidentes', to='catalogos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Registro de Incidente',
                'verbose_name_plural': 'Registros de Incidentes',
                'ordering': ['-fecha_incidente', '-fecha_registro'],
                'indexes': [models.Index(fields=['-fecha_incidente', 'maquina'], name='eventos_reg_fecha_i_278ced_idx'), models.Index(fields=['contexto_origen', 'fecha_incidente'], name='eventos_reg_context_9660be_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(db_index=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('se_realizo_mantenimiento', models.BooleanField()),
                ('tipo_mantenimiento', models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('AUTONOMO', 'Autónomo'), ('PREVENTIVO', 'Preventivo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('registro_materiales', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to='catalogos.maquina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to='catalogos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-fecha_mantenimiento', '-fecha_registro'],
                'indexes': [models.Index(fields=['-fecha_mantenimiento', 'maquina'], name='eventos_reg_fecha_m_76ec08_idx'), models.Index(fields=['maquina', 'tipo_mantenimiento'], name='eventos_reg_maquina_8b9b67_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('se_realizo_mantenimiento', True), ('descripcion__isnull', False), _connector='OR'), name='mantenimiento_requiere_descripcion')],
            },
        ),
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateField(db_index=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('hubo_produccion', models.BooleanField()),
                ('unidad_medida', models.CharField(choices=[('COMPRIMIDOS', 'Comprimidos'), ('KG', 'Kilogramos'), ('LITROS', 'Litros'), ('BLISTERS', 'Blisters')], max_length=20)),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.maquina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.producto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'ordering': ['-fecha_produccion', '-fecha_registro'],
                'indexes': [models.Index(fields=['-fecha_produccion', 'maquina'], name='eventos_reg_fecha_p_291ebd_idx'), models.Index(fields=['maquina', 'fecha_produccion', 'turno'], name='eventos_reg_maquina_5d271a_idx')],
                'constraints': [models.UniqueConstraint(fields=('maquina', 'fecha_produccion', 'turno'), name='unique_produccion_maquina_fecha_turno'), models.CheckConstraint(condition=models.Q(('cantidad_producida__gte', 0)), name='produccion_cantidad_no_negativa')],
            },
        ),
    ]
