# Generated by Django 5.2.7 on 2025-10-16 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_migrate_data_from_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_observacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('R', 'Rotativo')], max_length=2)),
                ('observaciones', models.TextField()),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación General',
                'verbose_name_plural': 'Observaciones Generales',
                'ordering': ['-fecha_observacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidente', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('R', 'Rotativo')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField()),
                ('acciones_correctivas', models.BooleanField(default=False)),
                ('detalle_acciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('contexto_origen', models.CharField(choices=[('PRODUCCION', 'Producción'), ('MANTENIMIENTO', 'Mantenimiento'), ('GENERAL', 'General')], max_length=20)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_incidentes', to='catalogos.maquina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_incidentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Incidente',
                'verbose_name_plural': 'Registros de Incidentes',
                'ordering': ['-fecha_incidente'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('R', 'Rotativo')], max_length=2)),
                ('se_realizo_mantenimiento', models.BooleanField()),
                ('tipo_mantenimiento', models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('AUTONOMO', 'Autónomo'), ('PREVENTIVO', 'Preventivo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('registro_materiales', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to='catalogos.maquina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-fecha_mantenimiento'],
            },
        ),
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('R', 'Rotativo')], max_length=2)),
                ('hubo_produccion', models.BooleanField()),
                ('unidad_medida', models.CharField(choices=[('COMPRIMIDOS', 'Comprimidos'), ('KG', 'Kilogramos'), ('LITROS', 'Litros'), ('BLISTERS', 'Blisters')], max_length=20)),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.maquina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.producto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'ordering': ['-fecha_produccion'],
            },
        ),
    ]
