version: '3.8'

services:
  # Backend Django
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: siprosapp-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./backend/logs:/app/backend/logs
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - DB_NAME=siprosa_mes
      - DB_USER=siprosa_user
      - DB_PASSWORD=siprosa_pass_123
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-dev-key-change-in-production-123456789
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,api
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000
      - THROTTLE_RATE_ANON=100/hour
      - THROTTLE_RATE_USER=1000/hour
      - LOGIN_THROTTLE_RATE=10/min
      - REGISTER_THROTTLE_RATE=5/hour
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@siprosa.com.ar
      - DJANGO_SUPERUSER_PASSWORD=Admin123456
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - siprosapp-network
    restart: unless-stopped

  # Frontend Next.js
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: siprosapp-web
    volumes:
      - ./frontend:/app
      - web-node-modules:/app/node_modules  # ← NOMBRADO (persiste)
      - web-next-cache:/app/.next         # ← NOMBRADO (persiste)
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # El navegador usa esta URL pública (visible en el bundle) para llamar al backend
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      # Next.js del lado del servidor resuelve el backend vía la red interna de Docker
      - NEXT_PUBLIC_API_URL_SERVER=http://api:8000
    depends_on:
      - api
    networks:
      - siprosapp-network
    restart: unless-stopped

  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: siprosapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: siprosa_mes
      POSTGRES_USER: siprosa_user
      POSTGRES_PASSWORD: siprosa_pass_123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siprosa_user -d siprosa_mes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - siprosapp-network

volumes:
  postgres-data:       # ← Datos de PostgreSQL
  web-node-modules:    # ← Persiste las dependencias npm
  web-next-cache:      # ← Persiste el caché de Next.js

networks:
  siprosapp-network:
    driver: bridge
