version: '3.8'

services:
  # Backend Django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siprosa_mes_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - DB_NAME=siprosa_mes
      - DB_USER=siprosa_user
      - DB_PASSWORD=siprosa_pass_123
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-dev-key-change-in-production-123456789
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - siprosa_network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: siprosa_mes_frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules  # ← NOMBRADO (persiste)
      - frontend_nextjs_cache:/app/.next         # ← NOMBRADO (persiste)
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # El navegador usa esta URL pública (visible en el bundle) para llamar al backend
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      # Next.js del lado del servidor resuelve el backend vía la red interna de Docker
      - NEXT_PUBLIC_API_URL_SERVER=http://web:8000
    depends_on:
      - web
    networks:
      - siprosa_network
    restart: unless-stopped

  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: siprosa_mes_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: siprosa_mes
      POSTGRES_USER: siprosa_user
      POSTGRES_PASSWORD: siprosa_pass_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siprosa_user -d siprosa_mes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - siprosa_network

volumes:
  postgres_data:
  frontend_node_modules:      # ← Persiste las dependencias npm
  frontend_nextjs_cache:      # ← Persiste el caché de Next.js

networks:
  siprosa_network:
    driver: bridge
