# Generated by Django 5.2.7 on 2025-10-05 05:00
# Migration inicial limpia - Django creará las tablas automáticamente

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Django creará todas las tablas automáticamente basándose en models.py
        # No necesitamos operaciones específicas aquí
    ]
