# Generated by Django 5.2.7 on 2025-10-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_quality_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicadorMantenimiento',
        ),
    ]
