# Generated by Django 5.2.7 on 2025-10-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('CANCELAR', 'Cancelar'), ('VER', 'Ver'), ('EXPORTAR', 'Exportar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_PROCESO', 'En Proceso'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado'), ('LIBERADO', 'Liberado')], default='PLANIFICADO', max_length=20),
        ),
    ]
