# Generated by Django 5.2.7 on 2025-10-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_indicadormantenimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestigacionIncidente',
        ),
    ]
