# Generated by Django 5.2.7 on 2025-10-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lote_cancelado_por_lote_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible en listado'),
        ),
    ]
