# Generated by Django 5.2.7 on 2025-10-07 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_desviacion_documentoversionado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='electronicsignature',
            name='core_electr_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='electronicsignature',
            new_name='core_electr_content_cfcd25_idx',
            old_name='core_electr_content_idx',
        ),
        migrations.RenameIndex(
            model_name='electronicsignature',
            new_name='core_electr_is_vali_074163_idx',
            old_name='core_electr_is_valid_idx',
        ),
        migrations.RemoveField(
            model_name='electronicsignature',
            name='data_to_sign',
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments'),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='data_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the signed data at the time of signing', max_length=64),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='password_hash',
            field=models.CharField(blank=True, default='', help_text='Hash of password used to authenticate (for audit purposes)', max_length=128),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REVIEW', 'Review'), ('RELEASE', 'Release'), ('REJECT', 'Reject'), ('AUTHORIZE', 'Authorize'), ('VERIFY', 'Verify')], help_text='Action being signed', max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='content_type',
            field=models.CharField(help_text="Type of object being signed (e.g., 'Lote', 'OrdenTrabajo')", max_length=100),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, help_text='When this signature was invalidated', null=True),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, help_text='User who invalidated this signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures_invalidated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='invalidation_reason',
            field=models.TextField(blank=True, help_text='Reason for invalidation'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which signature was applied', null=True),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Whether this signature is still valid'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='meaning',
            field=models.CharField(choices=[('APPROVED_BY', 'Approved by'), ('REVIEWED_BY', 'Reviewed by'), ('RELEASED_BY', 'Released by'), ('REJECTED_BY', 'Rejected by'), ('AUTHORIZED_BY', 'Authorized by'), ('VERIFIED_BY', 'Verified by')], help_text='Meaning of the signature', max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='object_id',
            field=models.IntegerField(help_text='ID of the object being signed'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='object_str',
            field=models.CharField(help_text='String representation of the object', max_length=200),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='reason',
            field=models.TextField(help_text='Reason for signing (required by 21 CFR Part 11)'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='signature_hash',
            field=models.CharField(blank=True, default='', editable=False, help_text='Hash of the signature itself (for integrity verification)', max_length=64),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the signature was applied'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='user',
            field=models.ForeignKey(help_text='User who signed', on_delete=django.db.models.deletion.PROTECT, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Browser/client user agent', max_length=500),
        ),
        migrations.AlterField(
            model_name='lotedocumento',
            name='hash_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='lotedocumento',
            name='tamaño_bytes',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['user', '-timestamp'], name='core_electr_user_id_9bd307_idx'),
        ),
        migrations.AlterModelTable(
            name='electronicsignature',
            table=None,
        ),
    ]
