// Generated by local openapi-typescript stub.
// This file captures a subset of the OpenAPI contract for TypeScript usage.

export interface CambiarPassword {
  "password_actual"?: string;
  "password_confirmacion": string;
  "password_nueva": string;
}

export interface CrearUsuario {
  "dni"?: string;
  "email": string;
  "fecha_ingreso"?: string;
  "first_name": string;
  "funcion_id"?: number;
  "is_staff"?: boolean;
  "is_superuser"?: boolean;
  "last_name": string;
  "legajo"?: string;
  "password": string;
  "password_confirmacion": string;
  "telefono"?: string;
  "turno_id"?: number;
  "username": string;
}

export interface EtapaProduccion {
  "activa"?: boolean;
  "codigo": string;
  "descripcion"?: string;
  "id"?: number;
  "maquinas_permitidas"?: number[];
  "maquinas_permitidas_nombres"?: string;
  "nombre": string;
  "parametros"?: number[];
  "parametros_nombres"?: string[];
}

export interface Formula {
  "activa"?: boolean;
  "codigo": string;
  "descripcion"?: string;
  "etapas"?: {
  "descripcion"?: string;
  "duracion_estimada_min"?: number;
  "etapa": number;
  "etapa_nombre"?: string;
  "id"?: number;
  "orden"?: number;
}[];
  "id"?: number;
  "ingredientes"?: {
  "cantidad": string;
  "id"?: number;
  "material": number;
  "material_nombre"?: string;
  "notas"?: string;
  "orden"?: number;
  "unidad": string;
}[];
  "producto": number;
  "producto_nombre"?: string;
  "version": string;
}

export interface Funcion {
  "activa"?: boolean;
  "codigo": string;
  "descripcion"?: string;
  "id"?: number;
  "nombre": string;
}

export interface Incidente {
  "acciones_correctivas"?: string;
  "created"?: string;
  "descripcion": string;
  "es_parada_no_planificada"?: boolean;
  "fecha_fin": string;
  "fecha_inicio": string;
  "id"?: number;
  "maquina"?: number;
  "maquina_detalle"?: string;
  "modified"?: string;
  "observaciones"?: string;
  "origen": "produccion" | "mantenimiento" | "general";
  "requiere_acciones_correctivas"?: boolean;
}

export interface Maquina {
  "activa"?: boolean;
  "año_fabricacion"?: number;
  "capacidad_nominal"?: string;
  "codigo": string;
  "descripcion"?: string;
  "documentos"?: {
  [key: string]: unknown;
};
  "fabricante"?: string;
  "fecha_instalacion"?: string;
  "id"?: number;
  "imagen"?: string;
  "modelo"?: string;
  "nombre": string;
  "numero_serie"?: string;
  "tipo": "COMPRESION" | "MEZCLADO" | "GRANULACION" | "EMBLISTADO" | "SERVICIOS";
  "tipo_display"?: string;
  "ubicacion": number;
  "ubicacion_nombre"?: string;
  "unidad_capacidad"?: string;
}

export interface MaquinaAttachment {
  "archivo": string;
  "content_type"?: string;
  "creado"?: string;
  "descripcion"?: string;
  "id"?: number;
  "maquina": number;
  "nombre"?: string;
  "subido_por"?: string;
  "tamano_bytes"?: number;
  "url"?: string;
}

export interface ObservacionGeneral {
  "creado_por"?: string;
  "fecha_hora"?: string;
  "id"?: number;
  "texto": string;
}

export interface Parametro {
  "activo"?: boolean;
  "codigo": string;
  "descripcion"?: string;
  "id"?: number;
  "nombre": string;
  "unidad"?: string;
}

export interface Producto {
  "activo"?: boolean;
  "codigo": string;
  "concentracion": string;
  "descripcion"?: string;
  "id"?: number;
  "imagen"?: string;
  "nombre": string;
  "presentacion": "BLISTER" | "FRASCO" | "POMO" | "AMPOLLA" | "SOBRE";
  "presentacion_display"?: string;
  "tipo": "COMPRIMIDO" | "CAPSULA" | "JARABE" | "INYECTABLE" | "CREMA";
  "tipo_display"?: string;
}

export interface RegistroMantenimiento {
  "descripcion": string;
  "descripcion_anomalias"?: string;
  "fecha_registro"?: string;
  "hora_fin": string;
  "hora_inicio": string;
  "id"?: number;
  "maquina": number;
  "observaciones"?: string;
  "registrado_por"?: string;
  "tiene_anomalias"?: boolean;
  "tipo_mantenimiento": "CORRECTIVO" | "AUTONOMO" | "PREVENTIVO";
}

export interface RegistroProduccion {
  "cantidad_producida"?: string;
  "estado"?: "CREADO" | "EN_PROCESO" | "COMPLETADO" | "CANCELADO";
  "fecha_registro"?: string;
  "formula": number;
  "hora_fin"?: string;
  "hora_inicio"?: string;
  "id"?: number;
  "maquina"?: number;
  "observaciones"?: string;
  "producto": number;
  "registrado_por"?: string;
  "turno"?: number;
  "unidad_medida"?: string;
}

export interface TokenObtainPair {
  "password": string;
  "username": string;
}

export interface TokenRefresh {
  "access"?: string;
  "refresh": string;
}

export interface Turno {
  "activo"?: boolean;
  "codigo": "M" | "T" | "N";
  "hora_fin": string;
  "hora_inicio": string;
  "id"?: number;
  "nombre": string;
  "nombre_display"?: string;
}

export interface Ubicacion {
  "activa"?: boolean;
  "codigo": string;
  "descripcion"?: string;
  "id"?: number;
  "maquinas_count"?: number;
  "nombre": string;
}

export interface UsuarioDetalle {
  "date_joined"?: string;
  "dni"?: string;
  "email": string;
  "fecha_ingreso"?: string;
  "first_name": string;
  "full_name"?: string;
  "funcion_id"?: number;
  "id"?: number;
  "is_active"?: boolean;
  "is_staff"?: boolean;
  "is_superuser"?: boolean;
  "last_login"?: string;
  "last_name": string;
  "legajo"?: string;
  "profile"?: string;
  "telefono"?: string;
  "turno_id"?: number;
  "username"?: string;
}

export interface UsuarioPerfil {
  "dni"?: string;
  "email": string;
  "first_name": string;
  "full_name"?: string;
  "funcion_id"?: number;
  "id"?: number;
  "last_name": string;
  "legajo"?: string;
  "profile"?: {
  "activo"?: boolean;
  "dni"?: string;
  "fecha_ingreso"?: string;
  "funcion_id"?: string;
  "funcion_nombre"?: string;
  "id"?: number;
  "legajo"?: string;
  "telefono"?: string;
  "turno_id"?: string;
  "turno_nombre"?: string;
  "usuario"?: {
  "email"?: string;
  "first_name"?: string;
  "full_name"?: string;
  "id"?: number;
  "is_staff"?: boolean;
  "is_superuser"?: boolean;
  "last_name"?: string;
  "username": string;
};
};
  "telefono"?: string;
  "turno_id"?: number;
  "username": string;
}

export interface Schemas {
  CambiarPassword: CambiarPassword;
  CrearUsuario: CrearUsuario;
  EtapaProduccion: EtapaProduccion;
  Formula: Formula;
  Funcion: Funcion;
  Incidente: Incidente;
  Maquina: Maquina;
  MaquinaAttachment: MaquinaAttachment;
  ObservacionGeneral: ObservacionGeneral;
  Parametro: Parametro;
  Producto: Producto;
  RegistroMantenimiento: RegistroMantenimiento;
  RegistroProduccion: RegistroProduccion;
  TokenObtainPair: TokenObtainPair;
  TokenRefresh: TokenRefresh;
  Turno: Turno;
  Ubicacion: Ubicacion;
  UsuarioDetalle: UsuarioDetalle;
  UsuarioPerfil: UsuarioPerfil;
}

export type Paths = Record<string, Record<string, unknown>>;
