# Generated by Django 5.2.7 on 2025-10-21 16:22

import backend.catalogos.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etapa de Producción',
                'verbose_name_plural': 'Etapas de Producción',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('version', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Use formato de versión como 1, 1.1 o 1.2.3 (solo números y puntos).', regex='^\\d+(?:\\.\\d+){0,2}$')])),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('ingredientes', models.JSONField(blank=True, default=list, help_text='Lista de ingredientes: [{material_id, cantidad, unidad}]')),
            ],
            options={
                'verbose_name': 'Fórmula',
                'verbose_name_plural': 'Fórmulas',
                'ordering': ['codigo', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('COMPRESION', 'Compresión'), ('MEZCLADO', 'Mezclado'), ('GRANULACION', 'Granulación'), ('EMBLISTADO', 'Emblistado'), ('SERVICIOS', 'Servicios')], max_length=20)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('año_fabricacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Fabricación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_capacidad', models.CharField(blank=True, help_text='ej: comprimidos/hora, kg/batch', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('documentos', models.JSONField(default=list, help_text='Lista de documentos: [{nombre, url}]')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(blank=True, help_text='Ej: kg, min, °C', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], db_index=True, max_length=1, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FormulaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('duracion_min', models.PositiveIntegerField(verbose_name='Duración (min)')),
                ('descripcion', models.TextField(blank=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.etapaproduccion')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.formula')),
            ],
            options={
                'verbose_name': 'Etapa de fórmula',
                'verbose_name_plural': 'Etapas de fórmula',
                'ordering': ['orden'],
                'unique_together': {('formula', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='etapas',
            field=models.ManyToManyField(related_name='formulas', through='catalogos.FormulaEtapa', to='catalogos.etapaproduccion'),
        ),
        migrations.AddField(
            model_name='etapaproduccion',
            name='maquinas_permitidas',
            field=models.ManyToManyField(blank=True, related_name='etapas_produccion', to='catalogos.maquina'),
        ),
        migrations.CreateModel(
            name='MaquinaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to=backend.catalogos.models.maquina_attachment_path)),
                ('nombre', models.CharField(blank=True, help_text='Nombre legible (opcional)', max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='catalogos.maquina')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de máquina',
                'verbose_name_plural': 'Adjuntos de máquina',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='etapaproduccion',
            name='parametros',
            field=models.ManyToManyField(blank=True, related_name='etapas', to='catalogos.parametro', verbose_name='Parámetros'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('tipo', models.CharField(choices=[('COMPRIMIDO', 'Comprimido'), ('CAPSULA', 'Cápsula'), ('JARABE', 'Jarabe'), ('INYECTABLE', 'Inyectable'), ('CREMA', 'Crema')], max_length=20)),
                ('presentacion', models.CharField(choices=[('BLISTER', 'Blister'), ('FRASCO', 'Frasco'), ('POMO', 'Pomo'), ('AMPOLLA', 'Ampolla'), ('SOBRE', 'Sobre')], max_length=20)),
                ('concentracion', models.CharField(help_text='ej: 500mg, 10mg/ml', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activo'], name='catalogos_p_codigo_c20f33_idx'), models.Index(fields=['nombre', 'activo'], name='catalogos_p_nombre_80210a_idx'), models.Index(fields=['tipo', 'activo'], name='catalogos_p_tipo_b627a4_idx')],
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='catalogos.producto'),
        ),
        migrations.CreateModel(
            name='ProductoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to=backend.catalogos.models.producto_attachment_path)),
                ('nombre', models.CharField(blank=True, help_text='Nombre legible (opcional)', max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='catalogos.producto')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de producto',
                'verbose_name_plural': 'Adjuntos de producto',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación física',
                'verbose_name_plural': 'Ubicaciones físicas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo', 'activa'], name='catalogos_u_codigo_6e9593_idx')],
            },
        ),
        migrations.AddField(
            model_name='maquina',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='catalogos.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='etapaproduccion',
            index=models.Index(fields=['codigo', 'activa'], name='catalogos_e_codigo_8e527f_idx'),
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['producto', 'activa'], name='catalogos_f_product_be2499_idx'),
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['codigo', 'version'], name='catalogos_f_codigo_3b6749_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formula',
            unique_together={('codigo', 'version')},
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['codigo', 'activa'], name='catalogos_m_codigo_a97dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['tipo', 'activa'], name='catalogos_m_tipo_70ddbd_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['ubicacion', 'activa'], name='catalogos_m_ubicaci_08b511_idx'),
        ),
    ]
