# Generated by Django 5.2.7 on 2025-10-16 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], db_index=True, max_length=1, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('tipo', models.CharField(choices=[('COMPRIMIDO', 'Comprimido'), ('CAPSULA', 'Cápsula'), ('JARABE', 'Jarabe'), ('INYECTABLE', 'Inyectable'), ('CREMA', 'Crema')], max_length=20)),
                ('presentacion', models.CharField(choices=[('BLISTER', 'Blister'), ('FRASCO', 'Frasco'), ('POMO', 'Pomo'), ('AMPOLLA', 'Ampolla'), ('SOBRE', 'Sobre')], max_length=20)),
                ('concentracion', models.CharField(help_text='ej: 500mg, 10mg/ml', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('documentos', models.JSONField(default=list, help_text='Lista de documentos: [{nombre, url}]')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activo'], name='catalogos_p_codigo_c20f33_idx'), models.Index(fields=['nombre', 'activo'], name='catalogos_p_nombre_80210a_idx'), models.Index(fields=['tipo', 'activo'], name='catalogos_p_tipo_b627a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('planta', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activa'], name='catalogos_u_codigo_6e9593_idx')],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('COMPRESION', 'Compresión'), ('MEZCLADO', 'Mezclado'), ('GRANULACION', 'Granulación'), ('EMBLISTADO', 'Emblistado'), ('SERVICIOS', 'Servicios')], max_length=20)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('año_fabricacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Fabricación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_capacidad', models.CharField(blank=True, help_text='ej: comprimidos/hora, kg/batch', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('requiere_calificacion', models.BooleanField(default=False, verbose_name='Requiere Calificación')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('documentos', models.JSONField(default=list, help_text='Lista de documentos: [{nombre, url}]')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='catalogos.ubicacion')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EtapaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_tipica', models.IntegerField(help_text='Duración típica en minutos', validators=[django.core.validators.MinValueValidator(1)])),
                ('requiere_validacion', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('parametros', models.JSONField(default=list, help_text='Lista de parámetros a controlar: [{nombre, tipo, min, max, unidad}]')),
                ('maquinas_permitidas', models.ManyToManyField(blank=True, related_name='etapas_produccion', to='catalogos.maquina')),
            ],
            options={
                'verbose_name': 'Etapa de Producción',
                'verbose_name_plural': 'Etapas de Producción',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activa'], name='catalogos_e_codigo_8e527f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duracion_tipica__gt', 0)), name='etapa_duracion_positiva')],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('version', models.CharField(choices=[('1.0', '1.0'), ('1.1', '1.1'), ('2.0', '2.0'), ('3.0', '3.0')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('tamaño_lote', models.IntegerField(help_text='Tamaño estándar del lote', validators=[django.core.validators.MinValueValidator(1)])),
                ('unidad', models.CharField(max_length=20)),
                ('tiempo_total', models.DecimalField(decimal_places=2, help_text='Tiempo total en horas', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('activa', models.BooleanField(default=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('ingredientes', models.JSONField(default=list, help_text='Lista de ingredientes: [{material_id, cantidad, unidad}]')),
                ('etapas', models.JSONField(default=list, help_text='Lista de etapas: [{etapa_id, duracion_min, descripcion}]')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='catalogos.producto')),
            ],
            options={
                'verbose_name': 'Fórmula',
                'verbose_name_plural': 'Fórmulas',
                'ordering': ['codigo', 'version'],
                'indexes': [models.Index(fields=['producto', 'activa'], name='catalogos_f_product_be2499_idx'), models.Index(fields=['codigo', 'version'], name='catalogos_f_codigo_3b6749_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tamaño_lote__gt', 0)), name='formula_tamaño_lote_positivo'), models.CheckConstraint(condition=models.Q(('tiempo_total__gt', 0)), name='formula_tiempo_positivo')],
                'unique_together': {('codigo', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['codigo', 'activa'], name='catalogos_m_codigo_a97dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['tipo', 'activa'], name='catalogos_m_tipo_70ddbd_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['ubicacion', 'activa'], name='catalogos_m_ubicaci_08b511_idx'),
        ),
    ]
