# Generated by Django 5.2.7 on 2025-10-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaetapa',
            name='duracion_min',
        ),
    ]
