# Generated by Django 5.2.7 on 2025-10-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Función",
                "verbose_name_plural": "Funciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="ubicacion",
            options={
                "ordering": ["planta", "nombre"],
                "verbose_name": "Ubicación física",
                "verbose_name_plural": "Ubicaciones físicas",
            },
        ),
    ]
