# Generated by Django 5.2.7 on 2025-10-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_funcion_alter_ubicacion_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=30, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "unidad",
                    models.CharField(
                        blank=True, help_text="Ej: kg, min, °C", max_length=20
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Parámetro",
                "verbose_name_plural": "Parámetros",
                "ordering": ["nombre"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="etapaproduccion",
            name="etapa_duracion_positiva",
        ),
        migrations.RemoveField(
            model_name="etapaproduccion",
            name="duracion_tipica",
        ),
        migrations.RemoveField(
            model_name="etapaproduccion",
            name="requiere_validacion",
        ),
        migrations.RemoveField(
            model_name="etapaproduccion",
            name="parametros",
        ),
        migrations.AddField(
            model_name="etapaproduccion",
            name="parametros",
            field=models.ManyToManyField(
                blank=True,
                related_name="etapas",
                to="catalogos.parametro",
                verbose_name="Parámetros",
            ),
        ),
    ]
