# Generated by Django 5.2.7 on 2025-10-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_remove_formulaetapa_duracion_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='ingredientes',
        ),
    ]
