# Generated by Django 5.2.7 on 2025-10-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_parametro_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ubicacion",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Ubicación física",
                "verbose_name_plural": "Ubicaciones físicas",
            },
        ),
        migrations.RemoveField(
            model_name="maquina",
            name="requiere_calificacion",
        ),
        migrations.RemoveField(
            model_name="ubicacion",
            name="planta",
        ),
    ]
