# Generated by Django 5.2.7 on 2025-10-21 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_remove_ingredientes_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulaetapa",
            name="duracion_estimada_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duración estimada en minutos para planificación.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulaetapa",
            name="formula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relaciones_etapas",
                to="catalogos.formula",
            ),
        ),
        migrations.CreateModel(
            name="FormulaIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unidad", models.CharField(max_length=20)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("notas", models.CharField(blank=True, max_length=255)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="catalogos.formula",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingrediente_de_formulas",
                        to="catalogos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente de fórmula",
                "verbose_name_plural": "Ingredientes de fórmula",
                "ordering": ["orden", "id"],
                "unique_together": {("formula", "orden", "material")},
            },
        ),
    ]
