# Generated by Django 5.2.7 on 2025-10-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0004_alter_ubicacion_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formula",
            name="formula_tamaño_lote_positivo",
        ),
        migrations.RemoveConstraint(
            model_name="formula",
            name="formula_tiempo_positivo",
        ),
        migrations.RemoveField(
            model_name="formula",
            name="aprobada",
        ),
        migrations.RemoveField(
            model_name="formula",
            name="tamaño_lote",
        ),
        migrations.RemoveField(
            model_name="formula",
            name="tiempo_total",
        ),
        migrations.RemoveField(
            model_name="formula",
            name="unidad",
        ),
        migrations.AlterField(
            model_name="formula",
            name="etapas",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de etapas: [{etapa_id, duracion_min, descripcion}]",
            ),
        ),
        migrations.AlterField(
            model_name="formula",
            name="ingredientes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de ingredientes: [{material_id, cantidad, unidad}]",
            ),
        ),
    ]
