# Generated by Django 5.2.7 on 2025-10-20 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0005_remove_formula_formula_tamaño_lote_positivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="version",
            field=models.CharField(
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use formato de versión como 1, 1.1 o 1.2.3 (solo números y puntos).",
                        regex="^\\d+(?:\\.\\d+){0,2}$",
                    )
                ],
            ),
        ),
    ]
