# Generated by Django 5.2.7 on 2025-10-20 05:25

import backend.catalogos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0006_alter_formula_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaquinaAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=500,
                        upload_to=backend.catalogos.models.maquina_attachment_path,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre legible (opcional)",
                        max_length=255,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("tamano_bytes", models.BigIntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="catalogos.maquina",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto de máquina",
                "verbose_name_plural": "Adjuntos de máquina",
                "ordering": ["-creado"],
            },
        ),
    ]
