# Generated by Django 5.2.7 on 2025-10-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación general',
                'verbose_name_plural': 'Observaciones generales',
            },
        ),
    ]
