# Generated by Django 5.2.7 on 2025-10-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('eventos', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('requiere_investigacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'verbose_name_plural': 'Tipos de Incidentes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroIncidente',
            fields=[
            ],
            options={
                'verbose_name': 'Registro de Incidente',
                'verbose_name_plural': 'Registros de Incidentes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eventos.registroincidente',),
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('severidad', models.CharField(choices=[('MENOR', 'Menor'), ('MODERADA', 'Moderada'), ('MAYOR', 'Mayor'), ('CRITICA', 'Crítica')], max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_INVESTIGACION', 'En Investigación'), ('ACCION_CORRECTIVA', 'Acción Correctiva'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_ocurrencia', models.DateTimeField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('impacto_produccion', models.TextField(blank=True)),
                ('impacto_calidad', models.TextField(blank=True)),
                ('impacto_seguridad', models.TextField(blank=True)),
                ('requiere_notificacion_anmat', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_cerrados', to=settings.AUTH_USER_MODEL)),
                ('lote_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='produccion.lote')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='catalogos.maquina')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='catalogos.ubicacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencias.tipoincidente')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
    ]
