# Generated by Django 5.2.7 on 2025-10-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0002_migrate_data_from_core"),
        ("incidencias", "0001_initial"),
        ("produccion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incidente",
            name="lote_afectado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidentes",
                to="produccion.lote",
            ),
        ),
        migrations.AddField(
            model_name="incidente",
            name="maquina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidentes",
                to="catalogos.maquina",
            ),
        ),
        migrations.AddField(
            model_name="incidente",
            name="reportado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidentes_reportados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incidente",
            name="ubicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidentes",
                to="catalogos.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="incidente",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="incidencias.tipoincidente",
            ),
        ),
    ]
