# Generated by Django 5.2.7 on 2025-10-16 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eventos.registroproduccion',),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True, verbose_name='Código de Lote')),
                ('cantidad_planificada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_producida', models.IntegerField(default=0)),
                ('cantidad_rechazada', models.IntegerField(default=0)),
                ('unidad', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_PROCESO', 'En Proceso'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado'), ('LIBERADO', 'Liberado')], default='PLANIFICADO', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('fecha_planificada_inicio', models.DateTimeField()),
                ('fecha_real_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_planificada_fin', models.DateTimeField()),
                ('fecha_real_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible en listado')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_cancelados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='catalogos.formula')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='catalogos.producto')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_supervisados', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='catalogos.turno')),
            ],
            options={
                'verbose_name': 'Lote de Producción',
                'verbose_name_plural': 'Lotes de Producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LoteEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, editable=False, null=True)),
                ('cantidad_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_merma', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_rendimiento', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('parametros_registrados', models.JSONField(default=list, help_text='Lista de parámetros: [{nombre, valor, unidad, conforme}]')),
                ('observaciones', models.TextField(blank=True)),
                ('requiere_aprobacion_calidad', models.BooleanField(default=False)),
                ('fecha_aprobacion_calidad', models.DateTimeField(blank=True, null=True)),
                ('aprobada_por_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.etapaproduccion')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='produccion.lote')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_ejecutadas', to='catalogos.maquina')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_operadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa de Lote',
                'verbose_name_plural': 'Etapas de Lotes',
                'ordering': ['lote', 'orden'],
                'unique_together': {('lote', 'orden')},
            },
        ),
    ]
