# Generated by Django 5.2.7 on 2025-10-21 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CREADO', 'Creado - Pendiente de procesar'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='CREADO', help_text='Estado actual del registro de producción', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales sobre la producción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la producción')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.formula')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.producto')),
                ('registrado_por', models.ForeignKey(editable=False, help_text='Usuario que registró la producción', on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de producción',
                'verbose_name_plural': 'Registros de producción',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroProduccionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(blank=True, help_text='Hora real de inicio de la etapa', null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.DateTimeField(blank=True, help_text='Hora real de finalización de la etapa', null=True, verbose_name='Hora de fin')),
                ('duracion_real', models.PositiveIntegerField(blank=True, help_text='Duración real de la etapa en minutos', null=True, verbose_name='Duración real (min)')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad procesada en esta etapa', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(blank=True, help_text='Unidad de medida para la cantidad', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas de esta etapa')),
                ('completada', models.BooleanField(default=False, help_text='Indica si la etapa está completada')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='catalogos.formulaetapa')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_etapas_produccion', to='catalogos.maquina')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='produccion.registroproduccion')),
            ],
            options={
                'verbose_name': 'Etapa de producción',
                'verbose_name_plural': 'Etapas de producción',
                'ordering': ['etapa__orden'],
            },
        ),
        migrations.AddIndex(
            model_name='registroproduccion',
            index=models.Index(fields=['estado'], name='produccion__estado_35e16f_idx'),
        ),
        migrations.AddIndex(
            model_name='registroproduccion',
            index=models.Index(fields=['producto'], name='produccion__product_328ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='registroproduccion',
            index=models.Index(fields=['formula'], name='produccion__formula_4203a0_idx'),
        ),
        migrations.AddIndex(
            model_name='registroproduccion',
            index=models.Index(fields=['registrado_por'], name='produccion__registr_1f1c11_idx'),
        ),
    ]
