# Generated by Django 5.2.7 on 2025-10-21 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0007_maquinaattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_inicio", models.DateTimeField()),
                ("hora_fin", models.DateTimeField()),
                (
                    "cantidad_producida",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[
                            ("COMPRIMIDOS", "Comprimidos"),
                            ("KILOGRAMOS", "Kilogramos"),
                            ("LITROS", "Litros"),
                            ("BLISTERS", "Blisters"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_produccion",
                        to="catalogos.formula",
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_produccion",
                        to="catalogos.maquina",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_produccion",
                        to="catalogos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de producción",
                "verbose_name_plural": "Registros de producción",
                "ordering": ("-hora_inicio", "-hora_fin"),
                "indexes": [
                    models.Index(
                        fields=["hora_inicio", "hora_fin"],
                        name="produccion__hora_in_db815c_idx",
                    ),
                    models.Index(
                        fields=["producto", "hora_inicio"],
                        name="produccion__product_3b3d1a_idx",
                    ),
                    models.Index(
                        fields=["maquina", "hora_inicio"],
                        name="produccion__maquina_f5a738_idx",
                    ),
                ],
            },
        ),
    ]
