# Generated by Django 5.2.7 on 2025-10-20 17:34

from django.conf import settings
from django.db import migrations, models


def ensure_registroproduccion_table(apps, schema_editor):
    """Garantiza que la tabla exista antes de manipular sus constraints."""

    model = apps.get_model("produccion", "RegistroProduccion")
    table_name = model._meta.db_table
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name not in existing_tables:
        schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0007_maquinaattachment"),
        ("produccion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            ensure_registroproduccion_table,
            migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="registroproduccion",
            options={
                "ordering": ("-registrado_en", "-hora_inicio", "-id"),
                "verbose_name": "Registro de producción",
                "verbose_name_plural": "Registros de producción",
            },
        ),
        migrations.RemoveConstraint(
            model_name="registroproduccion",
            name="produccion_registro_cantidad_mayor_cero",
        ),
        migrations.RemoveConstraint(
            model_name="registroproduccion",
            name="produccion_registro_hora_fin_mayor_inicio",
        ),
        migrations.RemoveIndex(
            model_name="registroproduccion",
            name="produccion_fecha__82798b_idx",
        ),
        migrations.RenameIndex(
            model_name="registroproduccion",
            new_name="produccion__maquina_7f2d05_idx",
            old_name="produccion_maquina__f02f6c_idx",
        ),
        migrations.RenameIndex(
            model_name="registroproduccion",
            new_name="produccion__product_328ea8_idx",
            old_name="produccion_producto_a765cb_idx",
        ),
        migrations.RenameIndex(
            model_name="registroproduccion",
            new_name="produccion__registr_7a1cd9_idx",
            old_name="produccion_registr_438e20_idx",
        ),
        migrations.RemoveField(
            model_name="registroproduccion",
            name="fecha_produccion",
        ),
        migrations.AddIndex(
            model_name="registroproduccion",
            index=models.Index(
                fields=["hora_inicio"], name="produccion__hora_in_b1930d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registroproduccion",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_producida__gt", 0)),
                name="produccion_registro_cantidad_mayor_cero",
            ),
        ),
        migrations.AddConstraint(
            model_name="registroproduccion",
            constraint=models.CheckConstraint(
                condition=models.Q(("hora_fin__gt", models.F("hora_inicio"))),
                name="produccion_registro_hora_fin_mayor_inicio",
            ),
        ),
    ]
