# Generated by Django 5.2.7 on 2025-10-21 21:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0004_formulaetapa_duracion_estimada_min_and_more"),
        ("produccion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registroproduccion",
            name="cantidad_producida",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cantidad total fabricada en la orden",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="registroproduccion",
            name="hora_fin",
            field=models.DateTimeField(
                blank=True,
                help_text="Hora programada o real de finalización",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registroproduccion",
            name="hora_inicio",
            field=models.DateTimeField(
                blank=True, help_text="Hora programada o real de inicio", null=True
            ),
        ),
        migrations.AddField(
            model_name="registroproduccion",
            name="maquina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_produccion",
                to="catalogos.maquina",
            ),
        ),
        migrations.AddField(
            model_name="registroproduccion",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_produccion",
                to="catalogos.turno",
            ),
        ),
        migrations.AddField(
            model_name="registroproduccion",
            name="unidad_medida",
            field=models.CharField(
                blank=True,
                help_text="Unidad de medida de la cantidad producida",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="registroproduccion",
            index=models.Index(
                fields=["maquina"], name="produccion__maquina_7f2d05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroproduccion",
            index=models.Index(fields=["turno"], name="produccion__turno_i_9afa9b_idx"),
        ),
    ]
