# Generated by Django 5.2.7 on 2025-10-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0002_migrate_data_from_core"),
        ("eventos", "0002_update_model_references"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Mantenimiento",
                "verbose_name_plural": "Tipos de Mantenimiento",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="RegistroMantenimiento",
            fields=[],
            options={
                "verbose_name": "Registro de Mantenimiento",
                "verbose_name_plural": "Registros de Mantenimiento",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eventos.registromantenimiento",),
        ),
        migrations.CreateModel(
            name="PlanMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "frecuencia_dias",
                    models.IntegerField(
                        blank=True, help_text="Frecuencia en días", null=True
                    ),
                ),
                (
                    "frecuencia_horas_uso",
                    models.IntegerField(
                        blank=True, help_text="Frecuencia en horas de uso", null=True
                    ),
                ),
                (
                    "frecuencia_ciclos",
                    models.IntegerField(
                        blank=True,
                        help_text="Frecuencia en ciclos de operación",
                        null=True,
                    ),
                ),
                (
                    "tareas",
                    models.JSONField(
                        default=list,
                        help_text="Lista de tareas: [{nombre, descripcion, duracion_min}]",
                    ),
                ),
                (
                    "repuestos_necesarios",
                    models.JSONField(
                        default=list,
                        help_text="Lista de repuestos: [{repuesto_id, cantidad}]",
                    ),
                ),
                (
                    "duracion_estimada_horas",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_mantenimiento",
                        to="catalogos.maquina",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mantenimiento.tipomantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Mantenimiento",
                "verbose_name_plural": "Planes de Mantenimiento",
                "ordering": ["maquina", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="OrdenTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("NORMAL", "Normal"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTA", "Abierta"),
                            ("ASIGNADA", "Asignada"),
                            ("EN_PROCESO", "En Proceso"),
                            ("PAUSADA", "Pausada"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABIERTA",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_planificada", models.DateTimeField(blank=True, null=True)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "duracion_real_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("trabajo_realizado", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("requiere_parada_produccion", models.BooleanField(default=False)),
                (
                    "costo_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_real",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "asignada_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_completadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_trabajo",
                        to="catalogos.maquina",
                    ),
                ),
                (
                    "plan_mantenimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_generadas",
                        to="mantenimiento.planmantenimiento",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mantenimiento.tipomantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Trabajo",
                "verbose_name_plural": "Órdenes de Trabajo",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("descripcion", models.TextField()),
                (
                    "tiempo_parada_horas",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_mantenimiento",
                        to="catalogos.maquina",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mantenimientos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orden_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="mantenimiento.ordentrabajo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mantenimiento.tipomantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Mantenimiento",
                "verbose_name_plural": "Historiales de Mantenimiento",
                "ordering": ["-fecha"],
            },
        ),
    ]
