# Generated by Django 5.2.7 on 2025-10-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(help_text='Hora real de inicio del mantenimiento', verbose_name='Hora de inicio')),
                ('hora_fin', models.DateTimeField(help_text='Hora real de finalización del mantenimiento', verbose_name='Hora de fin')),
                ('tipo_mantenimiento', models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('AUTONOMO', 'Autónomo'), ('PREVENTIVO', 'Preventivo')], max_length=20, verbose_name='Tipo de mantenimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del mantenimiento realizado', verbose_name='Descripción')),
                ('tiene_anomalias', models.BooleanField(default=False, help_text='Indica si se encontraron anomalías durante el mantenimiento', verbose_name='¿Se detectaron anomalías?')),
                ('descripcion_anomalias', models.TextField(blank=True, help_text='Descripción detallada de las anomalías encontradas (requerido si se detectaron anomalías)', verbose_name='Descripción de anomalías')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el mantenimiento', verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el mantenimiento')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to='catalogos.maquina', verbose_name='Máquina')),
                ('registrado_por', models.ForeignKey(editable=False, help_text='Usuario que registró el mantenimiento', on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de mantenimiento',
                'verbose_name_plural': 'Registros de mantenimiento',
                'ordering': ['-hora_inicio'],
                'indexes': [models.Index(fields=['hora_inicio', 'hora_fin'], name='mantenimien_hora_in_2fea54_idx'), models.Index(fields=['maquina'], name='mantenimien_maquina_c6f53c_idx'), models.Index(fields=['tipo_mantenimiento'], name='mantenimien_tipo_ma_6f047f_idx'), models.Index(fields=['registrado_por'], name='mantenimien_registr_8e9d64_idx'), models.Index(fields=['tiene_anomalias'], name='mantenimien_tiene_a_7987c7_idx')],
            },
        ),
    ]
