# Generated by Django 5.2.7 on 2025-10-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Legajo')),
                ('area', models.CharField(blank=True, choices=[('PRODUCCION', 'Producción'), ('MANTENIMIENTO', 'Mantenimiento'), ('ALMACEN', 'Almacén'), ('CALIDAD', 'Calidad'), ('ADMINISTRACION', 'Administración')], max_length=20, null=True)),
                ('turno_habitual', models.CharField(blank=True, choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('R', 'Rotativo')], max_length=2, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['user__username'],
            },
        ),
    ]
