# Generated by Django 5.2.7 on 2025-10-15 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "permisos",
                    models.JSONField(
                        default=dict, help_text="Estructura: {modulo: [acciones]}"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legajo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Legajo",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRODUCCION", "Producción"),
                            ("MANTENIMIENTO", "Mantenimiento"),
                            ("ALMACEN", "Almacén"),
                            ("CALIDAD", "Calidad"),
                            ("ADMINISTRACION", "Administración"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "turno_habitual",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Mañana"),
                            ("T", "Tarde"),
                            ("N", "Noche"),
                            ("R", "Rotativo"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                (
                    "asignado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_que_asigno",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="usuarios.rol",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Rol",
                "verbose_name_plural": "Asignaciones de Roles",
                "unique_together": {("usuario", "rol")},
            },
        ),
    ]
