# Generated by Django 5.2.7 on 2025-10-21 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,12}$', 'DNI debe tener 7 a 12 dígitos')])),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('funcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='catalogos.funcion')),
                ('turno_habitual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='catalogos.turno')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legajo__isnull', False), models.Q(('legajo', ''), _negated=True)), fields=('legajo',), name='usuarios_userprofile_legajo_unico')],
            },
        ),
    ]
