# Generated by Django 5.2.7 on 2025-10-20 02:26

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_funcion_alter_ubicacion_options"),
        ("usuarios", "0002_remove_userprofile_area_userprofile_funcion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dni",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{7,12}$", "DNI debe tener 7 a 12 dígitos"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="legajo",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("legajo__isnull", False), models.Q(("legajo", ""), _negated=True)
                ),
                fields=("legajo",),
                name="usuarios_userprofile_legajo_unico",
            ),
        ),
    ]
