# Generated by Django 5.2.7 on 2025-10-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_roles_migrate_to_groups'),
    ]

    operations = [
    ]
